# Generated by Django 3.0.1 on 2020-01-31 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('full_artists', models.TextField()),
                ('lyrics', models.TextField()),
                ('num_of_words', models.IntegerField()),
                ('num_of_swear_words', models.IntegerField()),
                ('url', models.URLField()),
                ('img_url', models.URLField()),
                ('header_url', models.URLField()),
                ('jewelry', models.IntegerField()),
                ('drugs', models.IntegerField()),
                ('reading_level_g', models.FloatField()),
                ('reading_level_f', models.TextField()),
                ('reading_level_p', models.FloatField()),
                ('adlibs', models.IntegerField()),
                ('lines', models.IntegerField()),
                ('syllables', models.IntegerField()),
                ('big_words', models.IntegerField()),
                ('sentence_length', models.IntegerField()),
            ],
        ),
    ]
