# Generated by Django 3.0.1 on 2020-01-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapAnalyzer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_words', models.IntegerField()),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('lyrics', models.TextField()),
                ('num_of_swear_words', models.IntegerField()),
                ('url', models.URLField()),
            ],
        ),
        migrations.DeleteModel(
            name='Song',
        ),
    ]
