# Generated by Django 3.0.1 on 2020-01-24 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapAnalyzer', '0002_auto_20200123_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='adlibs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='big_words',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='drugs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='jewelry',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='lines',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='reading_level_f',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='reading_level_g',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='reading_level_p',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='sentence_length',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='songdb',
            name='syllabes',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
