# Generated by Django 3.0.1 on 2020-01-27 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RapAnalyzer', '0004_auto_20200124_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songdb',
            name='url',
        ),
    ]
