# Generated by Django 3.0.1 on 2020-01-27 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapAnalyzer', '0005_remove_songdb_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='songdb',
            name='url',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
