# Generated by Django 3.0.1 on 2020-01-27 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapAnalyzer', '0006_songdb_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_words', models.IntegerField()),
                ('title', models.TextField()),
                ('artist', models.TextField()),
                ('lyrics', models.TextField()),
                ('num_of_swear_words', models.IntegerField()),
                ('url', models.TextField()),
                ('jewelry', models.IntegerField()),
                ('drugs', models.IntegerField()),
                ('reading_level_g', models.FloatField()),
                ('reading_level_f', models.TextField()),
                ('reading_level_p', models.FloatField()),
                ('adlibs', models.IntegerField()),
                ('lines', models.IntegerField()),
                ('syllables', models.IntegerField()),
                ('big_words', models.IntegerField()),
                ('sentence_length', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='SongDB',
        ),
    ]
