# Generated by Django 3.0.1 on 2020-01-27 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RapAnalyzer', '0006_songdb_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songdb',
            name='url',
            field=models.URLField(),
        ),
    ]
