# Generated by Django 3.0.1 on 2020-01-27 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RapAnalyzer', '0007_auto_20200127_0108'),
        ('RapAnalyzer', '0007_auto_20200127_0319'),
    ]

    operations = [
    ]
