# Generated by Django 3.0.1 on 2019-12-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receiveInput', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='input',
            old_name='input',
            new_name='text',
        ),
    ]
