# Generated by Django 3.0.1 on 2019-12-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receiveInput', '0002_auto_20191223_0055'),
    ]

    operations = [
        migrations.CreateModel(
            name='InputtedCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.TextField()),
                ('output', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Input',
        ),
    ]
